# Reference: https://github.com/i3/i3/blob/next/etc/config

enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

[mode.main.binding]
alt-enter = 'exec-and-forget open -n /System/Applications/Utilities/Terminal.app'

alt-j = 'focus left'
alt-k = 'focus down'
alt-l = 'focus up'
alt-semicolon = 'focus right'

alt-shift-semicolon = 'move right'

alt-h = ['split horizontal', '''exec-and-forget osascript <<EOF
    display notification "split horizontal" with title "aerospace"
EOF''']
alt-v = ['split vertical', '''exec-and-forget osascript <<EOF
    display notification "split vertical" with title "aerospace"
EOF''']


alt-f = ['fullscreen', '''exec-and-forget osascript <<EOF
    display notification "fullscreen" with title "aerospace"
EOF''']

alt-s = ['layout v_accordion', '''exec-and-forget osascript <<EOF
    display notification "vertical accordion" with title "aerospace"
EOF''']
alt-w = ['layout h_accordion', '''exec-and-forget osascript <<EOF
    display notification "horizontal accordion" with title "aerospace"
EOF''']
alt-e = ['layout tiles horizontal vertical', '''exec-and-forget osascript <<EOF
    display notification "toggle layout tiles -> horiz -> vert" with title "aerospace"
EOF''']

alt-shift-space = ['layout floating tiling', '''exec-and-forget osascript <<EOF
    display notification "toggle floating -> tiling" with title "aerospace"
EOF''']


# Not supported, because this command is redundant in AeroSpace mental model.
# See: https://nikitabobko.github.io/AeroSpace/guide#floating-windows
#alt-space = 'focus toggle_tiling_floating'

# `focus parent`/`focus child` are not yet supported, and it's not clear whether they
# should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
# alt-a = 'focus parent'

alt-1 = ['workspace 1', '''exec-and-forget osascript <<EOF
    display notification "workspace 1" with title "aerospace"
EOF''']
alt-2 = ['workspace 2', '''exec-and-forget osascript <<EOF
    display notification "workspace 2" with title "aerospace"
EOF''']
alt-3 = ['workspace 3', '''exec-and-forget osascript <<EOF
    display notification "workspace 3" with title "aerospace"
EOF''']
alt-4 = ['workspace 4', '''exec-and-forget osascript <<EOF
    display notification "workspace 4" with title "aerospace"
EOF''']
alt-5 = ['workspace 5', '''exec-and-forget osascript <<EOF
    display notification "workspace 5" with title "aerospace"
EOF''']
alt-6 = ['workspace 6', '''exec-and-forget osascript <<EOF
    display notification "workspace 6" with title "aerospace"
EOF''']
alt-7 = ['workspace 7', '''exec-and-forget osascript <<EOF
    display notification "workspace 7" with title "aerospace"
EOF''']
alt-8 = ['workspace 8', '''exec-and-forget osascript <<EOF
    display notification "workspace 8" with title "aerospace"
EOF''']
alt-9 = ['workspace 9', '''exec-and-forget osascript <<EOF
    display notification "workspace 9" with title "aerospace"
EOF''']
alt-0 = ['workspace 10', '''exec-and-forget osascript <<EOF
    display notification "workspace 10" with title "aerospace"
EOF''']

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-0 = 'move-node-to-workspace 10'

alt-shift-c = 'reload-config'

alt-r = 'mode resize'
# https://nikitabobko.github.io/AeroSpace/config-examples#default-config
alt-shift-h = ['join-with left', 'mode main']
alt-shift-l = ['join-with right', 'mode main']

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'
